#!/bin/sh
# =============================================================================
# scripts/report_gen.sh — build a self-contained HTML report from a results dir.
#
# Collects every *.txt file in the given directory and renders them into a
# single report.html with embedded CSS. HTML-escapes all content so tool output
# cannot inject markup.
#
# Usage: sh report_gen.sh <results_dir>
# =============================================================================
set -u

IKALI_SELF="$0"; export IKALI_SELF
IKALI_ROOT="${IKALI_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}"; export IKALI_ROOT
# shellcheck source=../lib/common.sh
. "$IKALI_ROOT/lib/common.sh"

DIR="${1:-}"
[ -n "$DIR" ] && [ -d "$DIR" ] || { log_error "Usage: sh report_gen.sh <results_dir>"; exit 1; }

OUT="$DIR/report.html"

# HTML-escape stdin: & < > only (sufficient inside <pre>).
html_escape() {
    sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

{
    cat <<'HEAD'
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>iKali Report</title>
<style>
 body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#0d1117;color:#c9d1d9}
 header{background:#161b22;padding:18px 22px;border-bottom:2px solid #30363d}
 h1{margin:0;font-size:20px;color:#58a6ff}
 .meta{color:#8b949e;font-size:13px;margin-top:4px}
 .card{margin:16px 22px;background:#161b22;border:1px solid #30363d;border-radius:8px;overflow:hidden}
 .card h2{margin:0;padding:10px 14px;font-size:15px;background:#21262d;color:#79c0ff;border-bottom:1px solid #30363d}
 pre{margin:0;padding:14px;white-space:pre-wrap;word-break:break-word;font-size:12.5px;line-height:1.45;color:#c9d1d9}
 footer{color:#8b949e;font-size:12px;padding:18px 22px;text-align:center}
</style></head><body>
<header><h1>iKali — Assessment Report</h1>
HEAD
    printf '<div class="meta">Directory: %s &middot; Generated: %s</div></header>\n' \
        "$(printf '%s' "$DIR" | html_escape)" "$(date '+%Y-%m-%d %H:%M:%S')"

    _found=0
    for f in "$DIR"/*.txt; do
        [ -f "$f" ] || continue
        _found=1
        _name="$(basename "$f")"
        printf '<div class="card"><h2>%s</h2><pre>' "$(printf '%s' "$_name" | html_escape)"
        html_escape < "$f"
        printf '</pre></div>\n'
    done
    [ "$_found" = "0" ] && printf '<div class="card"><h2>No data</h2><pre>No .txt result files found.</pre></div>\n'

    cat <<'FOOT'
<footer>Generated by iKali report_gen.sh — authorized testing only.</footer>
</body></html>
FOOT
} > "$OUT"

log_ok "Report written: $OUT"
